DEVICE_PATH := device/samsung/gta3xlwifi

# Asserts
TARGET_OTA_ASSERT_DEVICE := gta3xlwifi

# Kernel
TARGET_KERNEL_CONFIG := exynos7885-gta3xlwifi_defconfig

# Display
TARGET_SCREEN_DENSITY := 240

# Partitions
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 55574528
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5158993920
BOARD_CACHEIMAGE_PARTITION_SIZE := 157286400
BOARD_VENDORIMAGE_PARTITION_SIZE   := 452984832

# Inherit common board flags
include device/samsung/universal7885-common/BoardConfigCommon.mk

# SPL
VENDOR_SECURITY_PATCH := 2022-02-01

TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
